#
###################################
# Site wide configuration
####################################
#
title: hugofloresgarcia
email: hf01049@georgiasouthern.edu
description: it's me! i like to make weird music with beep beep boop boops
url: https://hugofloresgarcia.github.io/
keywords: ["blog", "jekyll"]
#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:title
port: 4001

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

collections:
   docs:
     output: true
#
###################################
# Site Owner configuration
####################################
#
owner:
  name: hugofloresgarcia
  avatar: flower_logo_v1_cropped.png
  job: ""
  bio: "it's me! i like to make weird music with beep beep boop boops"
  email: hf01049@georgiasouthern.edu
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: hugofloresgarcia/
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: hugo-f-a9617b130
  skype: #username
  xing: #username
  instagram: hugofloresgarcia
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
